apiVersion: v1
kind: Service
metadata:
  name: vue-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.labels}}
  type: {{.Values.service.type}} # service类型
  ports:
  - port: {{.Values.service.port}}
    nodePort: {{.Values.service.nodePort}} # 指定绑定的node的端口(默认的取值范围是：30000-32767), 如果不指定，会默认分配
    targetPort: {{.Values.service.targetPort}}
